name: oquare

# Controls when the workflow will run
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Evaluate ontologies
    steps:
      - uses: actions/checkout@v2
      # Configuration
      # Java setup
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
      # Python setup
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          
      - name: OQuaRE module
        uses: Emdien/oquare-metrics@v2
        with:
          ontology-folders: sounds/ontology
          ontology-files: ultimate-sounds-nomech.owl
          
      - name: Commit and push
        run: |
          git config --global user.name 'martinbremm'
          git config --global user.email 'm.bremm@student.maastrichtuniversity.nl'
          git add OQuaRE
          git commit -m "ontology quality assessment"
          git push || exit 0
