name: Generate SoundOntology documentation
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'ontology/SoundOntologyV3.owl'
    - '.github/workflows/SoundOntologyDoc.yml'
env:
  ONTOLOGY_FILE: ontology/SoundOntologyV3.owl
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install git+https://github.com/vemonet/Ontospy@improve-labels
        pip install "Ontospy==1.9.9.4" "Django==3.2.9" "Pygments==2.1.3"
        wget -O widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.15/widoco-1.4.15-jar-with-dependencies.jar
        mkdir -p docs/browse docs/tree docs/graph docs/lode

    - name: Generate docs with Widoco (LODE)
      run: |
        java -jar widoco.jar -ontFile $ONTOLOGY_FILE -outFolder docs/lode/ -getOntologyMetadata -oops -rewriteAll -webVowl -licensius -includeAnnotationProperties
    
    - name: Generate docs with Ontospy
      run: |
        ontospy gendocs -o docs/browse --type 2 --preflabel label --nobrowser $ONTOLOGY_FILE
        ontospy gendocs -o docs/tree --type 4 --preflabel label --nobrowser $ONTOLOGY_FILE
        ontospy gendocs -o docs/graph --type 10 --preflabel label --nobrowser $ONTOLOGY_FILE
    
    - name: Commit and push
      run: |
        git config --global user.name 'martinbremm'
        git config --global user.email 'm.bremm@student.maastrichtuniversity.nl'
        cp templates/description-en.html docs/lode/sections/description-en.html
        cp templates/references-en.html docs/lode/sections/references-en.html
        git fetch
        git checkout gh-pages
        # Remove all directory and files but docs
        rm -rf browse tree graph lode templates .github *.jar
        mv docs/* .
        rm -rf docs
        mv lode/* .
        mv index-en.html index.html
        find . -type f -exec sed -i "s/index-en\.html/index.html/g" {} +
        ls -alh
        git add .
        git commit -m "Automatically generate documentation from SoundOntology OWL ontology file using Ontospy and Widoco (lode)."
        git push || exit 0
    
    # - name: Hotfix graph nodes sizes in ontospy docs
    #   run: |
    #     find docs/graph/index.html -type f -exec sed -i "s/minNodeSize: 1,/minNodeSize: 2,/g" {} +
    #     find docs/graph/index.html -type f -exec sed -i "s/maxNodeSize: 30,/maxNodeSize: 24,/g" {} +
